"""Adding members, and admin groups.

Revision ID: 086dc480986c
Revises: 8acbad111ef6
Create Date: 2017-03-03 11:12:35.534600

"""

# revision identifiers, used by Alembic.
revision = '086dc480986c'
down_revision = '8acbad111ef6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # members who have a project have a member group added.
    op.execute('INSERT into users_groups (users_id, groups_id) SELECT users_id,2 FROM project')
    # users who have super=1, we add them to the admin group.
    op.execute('INSERT into users_groups (users_id, groups_id) SELECT id,1 FROM users WHERE super=1;')
    op.execute("INSERT into groups VALUES (11, 'commenter', 'Commenter', 11)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
