"""Adding active field to User

Revision ID: 0b16e0992d44
Revises: 0e8bf71a8d9f
Create Date: 2017-02-10 12:06:21.477343

"""

# revision identifiers, used by Alembic.
revision = '0b16e0992d44'
down_revision = '0e8bf71a8d9f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('users', 'passwd')
    op.execute("INSERT into groups values (10, 'newbie', 'Newbie', 10)")
    # NOTE: Commented out due to issue #38
    # op.execute("INSERT into users_groups values (95, 1)")
    op.execute("UPDATE users set active=True where id=95")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active')
    op.add_column('users', sa.Column('passwd', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.execute("DELETE from groups where id=10")
    # ### end Alembic commands ###
