"""Additional user fields. Social profiles.

Revision ID: 2c97c1c55e0b
Revises: c25a81c43821
Create Date: 2017-03-17 15:54:27.416366

"""

# revision identifiers, used by Alembic.
revision = '2c97c1c55e0b'
down_revision = 'c25a81c43821'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bitbucket_user', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('blog_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('github_user', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('registered_ip', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('twitter_user', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter_user')
    op.drop_column('users', 'registered_ip')
    op.drop_column('users', 'registered_at')
    op.drop_column('users', 'github_user')
    op.drop_column('users', 'blog_url')
    op.drop_column('users', 'bitbucket_user')
    # ### end Alembic commands ###
