"""Adding moderator group.

Revision ID: 51742dea4d0d
Revises: 2c97c1c55e0b
Create Date: 2017-03-23 17:50:42.090781

"""

# revision identifiers, used by Alembic.
revision = '51742dea4d0d'
down_revision = '2c97c1c55e0b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT into groups VALUES (12, 'moderator', 'Moderator', 12)")
    op.execute('INSERT into users_groups (users_id, groups_id) SELECT id,12 FROM users WHERE super=1;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
