"""news.summary field added

Revision ID: 6b5555b76772
Revises: 95639507ec8b
Create Date: 2018-08-10 16:33:20.320640

"""

# revision identifiers, used by Alembic.
revision = '6b5555b76772'
down_revision = '95639507ec8b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('summary', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'summary')
    # ### end Alembic commands ###
