"""Added foreign keys for users_groups

Revision ID: 71cf723fb7cb
Revises: c4e6d5863a94
Create Date: 2017-01-23 20:22:38.004696

"""

# revision identifiers, used by Alembic.
revision = '71cf723fb7cb'
down_revision = 'c4e6d5863a94'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_groups_users_id_fkey', 'users_groups', 'users', ['users_id'], ['id'])
    op.create_foreign_key('users_groups_groups_id_fkey', 'users_groups', 'groups', ['groups_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_groups_groups_id_fkey', 'users_groups', type_='foreignkey')
    op.drop_constraint('users_groups_users_id_fkey', 'users_groups', type_='foreignkey')
    # ### end Alembic commands ###
