"""wiki.locked added

Revision ID: 7bb2943bbcaf
Revises: 6b5555b76772
Create Date: 2018-08-14 17:36:25.271717

"""

# revision identifiers, used by Alembic.
revision = '7bb2943bbcaf'
down_revision = '6b5555b76772'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki', sa.Column('locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wiki', 'locked')
    # ### end Alembic commands ###
