"""Added is_spam, is_approved, is_deleted

Revision ID: 80bd213f4f54
Revises: d5833b09e4f5
Create Date: 2023-10-21 17:08:07.105353

"""

# revision identifiers, used by Alembic.
revision = '80bd213f4f54'
down_revision = 'd5833b09e4f5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_name_email_is_anonymous_uc', 'comment_author', ['name', 'email', 'is_anonymous'])
    op.add_column('project', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('is_spam', sa.Boolean(), nullable=True))
    op.add_column('projectcomment', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('projectcomment', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('projectcomment', sa.Column('is_spam', sa.Boolean(), nullable=True))
    op.add_column('release', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('release', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('release', sa.Column('is_spam', sa.Boolean(), nullable=True))
    op.add_column('tags', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('tags', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('tags', sa.Column('is_spam', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['name'])
    op.add_column('wiki', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('wiki', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('wiki', sa.Column('is_spam', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wiki', 'is_spam')
    op.drop_column('wiki', 'is_deleted')
    op.drop_column('wiki', 'is_approved')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('tags', 'is_spam')
    op.drop_column('tags', 'is_deleted')
    op.drop_column('tags', 'is_approved')
    op.drop_column('release', 'is_spam')
    op.drop_column('release', 'is_deleted')
    op.drop_column('release', 'is_approved')
    op.drop_column('projectcomment', 'is_spam')
    op.drop_column('projectcomment', 'is_deleted')
    op.drop_column('projectcomment', 'is_approved')
    op.drop_column('project', 'is_spam')
    op.drop_column('project', 'is_deleted')
    op.drop_column('project', 'is_approved')
    op.drop_constraint('_name_email_is_anonymous_uc', 'comment_author', type_='unique')
    # ### end Alembic commands ###
