"""adding news_alert table

Revision ID: d5833b09e4f5
Revises: e22b4355e6fd
Create Date: 2019-10-29 17:59:13.291912

"""

# revision identifiers, used by Alembic.
revision = 'd5833b09e4f5'
down_revision = 'e22b4355e6fd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary', sa.String(length=140), nullable=True),
    sa.Column('datetimeon', sa.DateTime(), nullable=True),
    sa.Column('submit_users_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('slug', name='news_alert_slug_key')
    )
    op.create_index('ix_news_alert_slug', 'news_alert', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_alert_slug', table_name='news_alert')
    op.drop_table('news_alert')
    # ### end Alembic commands ###
