"""Youtube, github, and patreon fields added to project.

Revision ID: e22b4355e6fd
Revises: 7bb2943bbcaf
Create Date: 2019-01-27 09:18:12.312081

"""

# revision identifiers, used by Alembic.
revision = 'e22b4355e6fd'
down_revision = '7bb2943bbcaf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('github_repo', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('patreon', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('youtube_trailer', sa.Text(), nullable=True))
    op.add_column('release', sa.Column('from_external', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'from_external')
    op.drop_column('project', 'youtube_trailer')
    op.drop_column('project', 'patreon')
    op.drop_column('project', 'github_repo')
    # ### end Alembic commands ###
